spring:
  mvc:
    favicon:
      enabled: true #关闭叶子图标

  jackson:
    date-format: yyyy-MM-dd #如果使用字符串表示，用这行设置格式
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///rk_resouces?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    encoding: UTF-8
server:
  port: 80
#mybatis
mybatis-plus:
  mapper-locations: classpath*:cn/zhy/resouese/mapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.zhy.resouese.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
  #  refresh-mapper: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#logging
logging:
  level: debug
  level.cn.zhy.resouese.mapper: DEBUG